[profile.default]
src = "src"
out = "out"
libs = ["lib", "lib/forge-std", "lib/openzeppelin-contracts", "lib/chainlink-evm"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-evm"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
